name: g2c
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: '>=2.18.2 <3.0.0'
dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  firebase_core: ^1.24.0
  firebase_database: ^9.1.7

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:


  uses-material-design: true
  assets:
    - assets/

  fonts:
   - family: VarelaRound
     fonts:
       - asset: fonts/VarelaRound-Regular.ttf